steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder:v1', '--path', 'samples/nodejs', '--publish', 'gcr.io/$PROJECT_ID/node-bot:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image=gcr.io/$PROJECT_ID/node-bot:$COMMIT_SHA', '--platform=managed', '--project=$PROJECT_ID', '--region=australia-southeast1-a', '--allow-unauthenticated', '--memory=256Mi', 'node-bot']
